data_dir: data
raw_dir: ${data_dir}/raw
processed_dir: ${data_dir}/processed

datasets:
  rm_stopwords: False
  raw:
    train: ${raw_dir}/train.csv
    dev: ${raw_dir}/dev.csv
    test: ${raw_dir}/test.csv
  processed:
    train: ${processed_dir}/processed_train.csv
    dev: ${processed_dir}/processed_dev.csv
    test: ${processed_dir}/processed_test.csv

features:
  X_col: processed_text
  y_col: label
  max_seq_len: 110
  batch_size: 32
  word_vec_dim: 300

model:
  learning_rate: 0.001
  max_epochs: 3
